import React, { useState, useCallback } from 'react';

const styles = {
  container: {
    minHeight: '100vh',
    background: '#070c16',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
    fontFamily: 'Outfit, sans-serif',
  },
  card: {
    width: '100%',
    maxWidth: 540,
    background: '#0d1422',
    borderRadius: 16,
    border: '1px solid rgba(232, 150, 42, 0.12)',
    padding: '32px 24px',
  },
  iconRow: {
    textAlign: 'center',
    marginBottom: 16,
  },
  icon: {
    width: 48,
    height: 48,
    borderRadius: '50%',
    background: 'rgba(232, 150, 42, 0.1)',
    border: '1px solid rgba(232, 150, 42, 0.2)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 22,
  },
  title: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 22,
    fontWeight: 700,
    color: '#E2E8F0',
    textAlign: 'center',
    margin: '0 0 24px 0',
  },
  notice: {
    background: '#121b2d',
    borderRadius: 12,
    border: '1px solid rgba(232, 150, 42, 0.12)',
    padding: '20px',
    marginBottom: 20,
  },
  noticeText: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 14,
    color: '#E2E8F0',
    lineHeight: 1.7,
    margin: 0,
  },
  warningBox: {
    background: 'rgba(224, 104, 32, 0.08)',
    borderRadius: 12,
    border: '1px solid rgba(224, 104, 32, 0.2)',
    padding: '16px 20px',
    marginBottom: 24,
  },
  warningTitle: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 14,
    fontWeight: 600,
    color: '#e06820',
    margin: '0 0 6px 0',
  },
  warningText: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 13,
    color: '#8890AB',
    lineHeight: 1.6,
    margin: 0,
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 20,
    cursor: 'pointer',
  },
  checkbox: {
    width: 22,
    height: 22,
    minWidth: 22,
    minHeight: 22,
    borderRadius: 6,
    border: '2px solid rgba(232, 150, 42, 0.3)',
    background: '#121b2d',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    cursor: 'pointer',
    flexShrink: 0,
  },
  checkboxChecked: {
    background: '#e8962a',
    borderColor: '#e8962a',
  },
  checkmark: {
    color: '#070c16',
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1,
  },
  checkboxLabel: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 14,
    color: '#E2E8F0',
    lineHeight: 1.5,
    cursor: 'pointer',
  },
  button: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 16,
    fontWeight: 600,
    color: '#070c16',
    background: 'linear-gradient(135deg, #e8962a, #ffc15a)',
    border: 'none',
    borderRadius: 12,
    padding: '14px 24px',
    width: '100%',
    minHeight: 48,
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  buttonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  backButton: {
    fontFamily: 'Outfit, sans-serif',
    fontSize: 14,
    fontWeight: 500,
    color: '#8890AB',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '12px 24px',
    minHeight: 44,
    marginTop: 12,
    width: '100%',
    textAlign: 'center',
  },
};

const LegalDisclaimer = React.memo(function LegalDisclaimer({ onAccept, onBack }) {
  const [acknowledged, setAcknowledged] = useState(false);

  const handleAccept = useCallback(() => {
    if (!acknowledged) return;
    onAccept();
  }, [acknowledged, onAccept]);

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <div style={styles.iconRow}>
          <div style={styles.icon}>
            <span role="img" aria-hidden="true">&#9888;</span>
          </div>
        </div>

        <h1 style={styles.title}>Before You Begin</h1>

        <div style={styles.notice}>
          <p style={styles.noticeText}>
            Analysis results are generated by advanced computer vision technology
            for educational and training purposes only. Results are not official
            USAG scores and should not replace qualified coaching.
          </p>
        </div>

        <div style={styles.warningBox}>
          <p style={styles.warningTitle}>Safety Notice</p>
          <p style={styles.warningText}>
            Always train under qualified supervision. Consult your coach before
            making changes to technique or training routines based on analysis
            results.
          </p>
        </div>

        <div
          style={styles.checkboxRow}
          onClick={() => setAcknowledged((v) => !v)}
          role="checkbox"
          aria-checked={acknowledged}
          aria-label="I understand these results are for practice feedback only"
          tabIndex={0}
          onKeyDown={(e) => {
            if (e.key === ' ' || e.key === 'Enter') {
              e.preventDefault();
              setAcknowledged((v) => !v);
            }
          }}
        >
          <div style={{ ...styles.checkbox, ...(acknowledged ? styles.checkboxChecked : {}) }}>
            {acknowledged && <span style={styles.checkmark}>&#10003;</span>}
          </div>
          <span style={styles.checkboxLabel}>
            I understand these results are for practice feedback only
          </span>
        </div>

        <button
          style={{
            ...styles.button,
            ...(acknowledged ? {} : styles.buttonDisabled),
          }}
          onClick={handleAccept}
          disabled={!acknowledged}
          aria-label="Continue"
        >
          Continue
        </button>

        {onBack && (
          <button
            style={styles.backButton}
            onClick={onBack}
            aria-label="Go back"
          >
            Back
          </button>
        )}
      </div>
    </div>
  );
});

export default LegalDisclaimer;
